// ELEMENT VII – Operating Procedures
// Format: { q: "Question?", a: ["A. choice","B. choice","C. choice","D. choice"], correct: index_of_correct }

const originalQuestions = [
  { q: "The Readability Signal Tone (RST) reporting system is based on a scale of _________ for readability", a: ["A. 0-3","B. 0-5","C. 0-7","D. 0-9"], correct: 1 },
  { q: "The RST reporting system for signal strength and tone is based on a scale of", a: ["A. 0-5","B. 0-7","C. 0-9","D. 1-10"], correct: 2 },
  { q: "What frequency band is most usable for line of sight propagation", a: ["A. 3-30 MHz","B. 30-300 MHz","C. 300-3000 MHz","D. HF band"], correct: 1 },
  { q: "Maximum power authorized for CW transmission on HF Fixed Station for Class B licensee", a: ["A. 100 W","B. 500 W","C. 1 kW","D. 50 W"], correct: 1 },
  { q: "For uniformity in international communication, the time measurement standard used at present is", a: ["A. GMT","B. UTC","C. Local Time","D. PST"], correct: 1 },
  { q: "To facilitate the reception of distress call, all transmissions on 145 MHz shall be kept a minimum and shall not exceed", a: ["A. 1 minute","B. 2 minutes","C. 30 seconds","D. 5 minutes"], correct: 0 },
  { q: "Maximum power authorized for class B licensee operating on VHF", a: ["A. 100 W","B. 500 W","C. 1 kW","D. No specified limit"], correct: 3 },
  { q: "What is the common code used in Amateur Radiotelephony for Atmospheric interference", a: ["A. QRM","B. QRN","C. QSB","D. QSP"], correct: 0 },
  { q: "What is the common code used in Amateur Radiotelephony for Message relay", a: ["A. QSP","B. QRM","C. QRZ","D. QSB"], correct: 0 },
  { q: "What is the common code used in Amateur Radiotelephony for “Who is this?”", a: ["A. QSB","B. QRN","C. QRZ","D. QRM"], correct: 2 },
  { q: "What is the common code used in Amateur Radiotelephony for “Signal Strength Varies?”", a: ["A. QRZ","B. QSB","C. QRM","D. QSP"], correct: 1 },
  { q: "After calling a certain station and he does not give an answer, you are allowed to make", a: ["A. 1 call","B. 2 calls","C. 3 calls","D. 4 calls"], correct: 2 },
  { q: "The basic single side band demodulator is known as", a: ["A. Mixer","B. Product Detector","C. Balanced Modulator","D. Phase Detector"], correct: 1 },
  { q: "For repeater operation, it is good operating procedure to leave a pause between overs. The accepted interval is normally _________ seconds.", a: ["A. 1","B. 2","C. 3","D. 5"], correct: 2 },
  { q: "The voice equivalent of “break-in” is", a: ["A. VOX","B. CW","C. SSB","D. AM"], correct: 0 },
  { q: "The television standard used for color system in the Philippines", a: ["A. PAL","B. SECAM","C. American National Television Standards Committee","D. DVB"], correct: 2 },
  { q: "What is the number of lines per frame of TV transmission in the Philippines?", a: ["A. 625 lines","B. 525 lines per frame","C. 405 lines","D. 1080 lines"], correct: 1 },
  { q: "If it is 3:00 PM in the Philippines, what is it in UTC?", a: ["A. 0600 UTC","B. 0700 UTC","C. 0800 UTC","D. 0900 UTC"], correct: 1 },
  { q: "To overcome difficulty in spelling _____ are used by radio amateur operators.", a: ["A. Numbers","B. Phonetic alphabet","C. Morse codes","D. Call signs"], correct: 1 },
  { q: "The best way to orient your antenna beam when making long distance communication is to use", a: ["A. Compass","B. Great Circle Map","C. GPS","D. Magnetic North"], correct: 1 },
  { q: "When you are inviting amateur stations to transmit on the working frequency, you may send in telegraphy the letter", a: ["A. K","B. Q","C. C","D. V"], correct: 0 },
  { q: "The calling frequency in the 40 meter band in the Philippines is", a: ["A. 7.045 MHz","B. 7.150 MHz","C. 7.200 MHz","D. 7.000 MHz"], correct: 0 },
  { q: "SSB Modulation is classified as", a: ["A. Frequency","B. Amplitude","C. Phase","D. Pulse"], correct: 1 },
  { q: "A frequency band most useful for skywave propagation", a: ["A. VHF","B. HF","C. UHF","D. SHF"], correct: 1 },
  { q: "Identical or matched impedance of transmission line and antenna will result in", a: ["A. High SWR","B. Low SWR","C. Unity SWR","D. Infinite SWR"], correct: 2 },
  { q: "A radio wave 10 m long has a frequency equal to or approximately", a: ["A. 3 MHz","B. 30 MHz","C. 300 MHz","D. 3000 MHz"], correct: 1 },
  { q: "Frequency modulated by voice is represented by the symbol", a: ["A. F1","B. F2","C. F3","D. A3"], correct: 2 },
  { q: "Property of receiver to discriminate against desired and undesired signal", a: ["A. Sensitivity","B. Selectivity","C. Fidelity","D. Stability"], correct: 1 },
  { q: "A device used in SSB operation that suppresses the carrier of an SSB transmitter", a: ["A. Mixer","B. Balanced Modulator","C. Product Detector","D. Oscillator"], correct: 1 },
  { q: "What is the length of the fourth harmonic of a 2-meter long radio signal?", a: ["A. 2 m","B. 1 m","C. 0.5 m","D. 0.25 m"], correct: 2 },
  { q: "The name of any station is", a: ["A. QRA","B. QRZ","C. QRM","D. QSB"], correct: 0 },
  { q: "Who is calling me?", a: ["A. QRA","B. QRZ","C. QRM","D. QSB"], correct: 1 },
  { q: "I am troubled with static", a: ["A. QRN","B. QRM","C. QSB","D. QSP"], correct: 0 },
  { q: "Will you relay my message?", a: ["A. QRM","B. QSP","C. QRZ","D. QSB"], correct: 1 },
  { q: "The use of two breaks in joining an on-going conversation indicates", a: ["A. There is urgency or priority traffic","B. Request for signal report","C. End of transmission","D. Station identification"], correct: 0 },
  { q: "In RTTY transmission, frequency shift shall not exceed", a: ["A. 450 Hz","B. 850 Hz","C. 1200 Hz","D. 300 Hz"], correct: 1 },
  { q: "The simultaneous transmission of sound and picture as in amateur television maybe allowed by the NTC on all frequencies __________ MHz.", a: ["A. Above 30","B. Above 60","C. Above 90","D. Above 120"], correct: 1 },
  { q: "Maximum power that can be allowed for Class B amateurs on SSB, suppressed carrier is", a: ["A. 500 W pep","B. 1 kW pep","C. 100 W pep","D. 2 kW pep"], correct: 1 },
  { q: "When it is 11:00 PM in the Philippines, it is equivalent to", a: ["A. 1300 UTC","B. 1400 UTC","C. 1500 UTC","D. 1600 UTC"], correct: 2 },
  { q: "Single side band modulation is classified under", a: ["A. AM","B. FM","C. PM","D. CW"], correct: 0 }
];
