// ELEMENT VI – Circuit Components
// Format: { q: "Question?", a: ["A. choice","B. choice","C. choice","D. choice"], correct: index_of_correct }

const originalQuestions = [
  { q: "A vacuum tube having a suppressor grid", a: ["A. Triode","B. Tetrode","C. Pentode","D. Diode"], correct: 2 },
  { q: "A carbon resistor with color bands yellow, green and red has a value equal to", a: ["A. 450 ohms","B. 4,500 ohms","C. 45 ohms","D. 4,000 ohms"], correct: 1 },
  { q: "Two capacitors valued at 400 and 600 uF consecutively are connected in series in an electric circuit. What is the value of its equivalent capacitance?", a: ["A. 240 uF","B. 500 uF","C. 1000 uF","D. 200 uF"], correct: 0 },
  { q: "The ratio of change in plate current and the grid voltage of a triode amplifier, keeping its plate resistance constant is the", a: ["A. Amplification factor","B. Plate resistance","C. Transconductance of the vacuum tube","D. Gain"], correct: 2 },
  { q: "Three identical inductors valued at 90 millihenrys are connected in parallel. The total equivalent inductance is equal to", a: ["A. 90 mH","B. 30 mH","C. 270 mH","D. 45 mH"], correct: 1 },
  { q: "A vacuum tube having a filament, anode, cathode, and control grid is", a: ["A. Diode","B. Tetrode","C. Triode","D. Pentode"], correct: 2 },
  { q: "The symbol used to designate amplification factor of a VT amplifier", a: ["A. Beta","B. MU","C. Alpha","D. Gm"], correct: 1 },
  { q: "Commonly used diode as RF switch", a: ["A. Zener","B. PIN","C. Tunnel","D. Schottky"], correct: 1 },
  { q: "The three terminals of a silicon-controlled rectifier (SCR) are the anode, cathode and", a: ["A. Gate","B. Base","C. Collector","D. Emitter"], correct: 0 },
  { q: "Type of diodes normally used in voltage regulator circuits", a: ["A. Schottky","B. Tunnel","C. Zener","D. Varactor"], correct: 2 },
  { q: "What is the forward resistance of an ideal diode", a: ["A. Zero","B. Infinite","C. One ohm","D. Ten ohms"], correct: 0 },
  { q: "What diode has a negative resistance?", a: ["A. Zener","B. PIN","C. Tunnel","D. Schottky"], correct: 2 },
  { q: "A vacuum tube having a filament, a cathode and anode is", a: ["A. Diode","B. Triode","C. Tetrode","D. Pentode"], correct: 0 },
  { q: "A vacuum tube having a filament, a cathode, anode, and control grid", a: ["A. Triode","B. Diode","C. Pentode","D. Tetrode"], correct: 0 },
  { q: "Rayleigh fading occurs several times per minute during", a: ["A. Ionospheric propagation","B. Troposcatter","C. Skywave","D. Groundwave"], correct: 1 },
  { q: "Two inductors valued at 30 H and 60 H respectively are connected in parallel. What is the total equivalent inductance?", a: ["A. 20 H","B. 30 H","C. 90 H","D. 15 H"], correct: 0 },
  { q: "Two capacitors valued at 40 uF and 60 uF are connected in series, the total equivalent capacitance?", a: ["A. 20 uF","B. 24 uF","C. 50 uF","D. 100 uF"], correct: 1 },
  { q: "The Beta of a transistor is its", a: ["A. Voltage gain","B. Current amplification factor","C. Power gain","D. Resistance ratio"], correct: 1 },
  { q: "The sub-harmonic of 1000 kHz", a: ["A. 2000 kHz","B. 500 kHz","C. 250 kHz","D. 1500 kHz"], correct: 1 },
  { q: "A conductive circuit pattern applied to one or both sides of an insulating substrate is known as", a: ["A. Breadboard","B. Printed circuit","C. Strip board","D. Veroboard"], correct: 1 },
  { q: "3 dB points are also known as", a: ["A. Half-power points","B. Full-power points","C. Quarter-power points","D. Gain margin"], correct: 0 },
  { q: "What is the capacitive reactance of a capacitor whose value is 350 pF, operating on frequency 1200 kHz?", a: ["A. 379 ohms","B. 120 ohms","C. 600 ohms","D. 1000 ohms"], correct: 0 },
  { q: "A series circuit consists of an inductance of 500 uH and a capacitance of 400 pF. What is the resonant frequency?", a: ["A. 356 kHz","B. 100 kHz","C. 500 kHz","D. 1 MHz"], correct: 0 },
  { q: "The majority carrier in P-type semiconductor materials", a: ["A. Electron","B. Hole","C. Proton","D. Ion"], correct: 1 },
  { q: "What is the majority carrier in N-type semiconductor material?", a: ["A. Electron","B. Hole","C. Proton","D. Ion"], correct: 0 },
  { q: "Diodes normally used to low frequency due to its high internal capacitance", a: ["A. Junction","B. PIN","C. Zener","D. Tunnel"], correct: 0 },
  { q: "In semiconductor circuit, the ratio of collector current to base current is known", a: ["A. Alpha","B. Beta","C. Gamma","D. Mu"], correct: 1 },
  { q: "The minority carrier in N-type semi-conductor material", a: ["A. Holes","B. Electrons","C. Protons","D. Neutrons"], correct: 0 },
  { q: "A common semi-conductor diode used as radio frequency switch", a: ["A. Zener","B. PIN","C. Tunnel","D. Schottky"], correct: 1 },
  { q: "A type of semi-conductor diode having a negative resistance region", a: ["A. PIN","B. Tunnel","C. Zener","D. Varactor"], correct: 1 },
  { q: "An electronic semi-conductor component capable of controlling electron flow through it is known as", a: ["A. Resistor","B. Solid-state device","C. Capacitor","D. Inductor"], correct: 1 },
  { q: "A disadvantage of using semi-conductor as against vacuum tubes", a: ["A. Low heat resistance","B. High power consumption","C. Large size","D. High cost"], correct: 0 },
  { q: "Doping germanium with gallium causes", a: ["A. Electron current flow","B. Hole current flow","C. Photon emission","D. Increased resistance"], correct: 1 },
  { q: "Solid state lamps are also known as", a: ["A. Fluorescent","B. LED","C. Neon","D. Incandescent"], correct: 1 },
  { q: "An emitter follower transistor amplifier circuit is also known as", a: ["A. Common-collector","B. Common-emitter","C. Common-base","D. Differential"], correct: 0 },
  { q: "A varactor is", a: ["A. Variable capacitor diode","B. Voltage regulator","C. Current limiter","D. Rectifier"], correct: 0 },
  { q: "What is a photo junction device?", a: ["A. Solid-state device that increases its conductance when struck by protons of light or heat","B. Voltage regulator","C. Current amplifier","D. Oscillator"], correct: 0 },
  { q: "The three basic parts of transistors are the base, the collector and the", a: ["A. Emitter","B. Gate","C. Anode","D. Source"], correct: 0 },
  { q: "The two very useful semi-conductors are germanium and", a: ["A. Silicon","B. Carbon","C. Aluminum","D. Copper"], correct: 0 },
  { q: "Zener diodes are diodes", a: ["A. That operate on its avalanche voltage","B. That rectify AC","C. That amplify current","D. That work only in forward bias"], correct: 0 },
  { q: "The greatest advantage of a transistor over a vacuum tube is", a: ["A. Size","B. Heat resistance","C. High voltage tolerance","D. Complexity"], correct: 0 }
];

