const originalQuestions = [
  {
    q: "Given a low power output transistor stage having a collector impedance of 1250 ohms, what will be the best transformer turns ratio to use to couple it to a 50 ohm antenna?",
    a: ["125:05:00", "5:01", "25:01:00", "10:01"],
    correct: 0
  },
  {
    q: "In general we expect a circuit composed of common emitter NPN audio transistor amplifier stages to have __________",
    a: ["positive ground", "negative ground", "earthed ground", "no ground connection"],
    correct: 1
  },
  {
    q: "What is an electronic component that resist the flow of current in a circuit used to provide bias or voltage drop?",
    a: ["Resistor", "Diode", "Ferrite Core", "Fuse"],
    correct: 0
  },
  {
    q: "The 1N34A germanium diode is the component of choice when it comes to signal detection or demodulation of AM signals. Silicon diodes are not used for this because __________",
    a: [
      "they are more expensive",
      "they have a higher breakdown voltage",
      "they generally have a higher barrier potential",
      "they don’t work as well above 60Hz"
    ],
    correct: 3
  },
  {
    q: "The majority carrier in an N-type semi conductor is __________",
    a: ["electrons", "holes", "neutrons", "protons"],
    correct: 0
  },
  {
    q: "Like a safety pin on a grenade, what device should always be shunted to a large high voltage electrolytic capacitor when handled by personnel in repairing equipment which has been energized?",
    a: [
      "rectifier diode across the terminals",
      "a small decoupling capacitor",
      "zener diode",
      "resistor"
    ],
    correct: 1
  },
  {
    q: "What is a meter used to measure current and is connected in series to the circuit?",
    a: ["Barometer", "Ammeter", "Voltmeter", "Galvanometer"],
    correct: 1
  },
  {
    q: "What type of diode usually made of silicon material and intended for rectification purposes, i.e., converting an alternating current to direct current in DC power supplies?",
    a: ["Zener Diode", "Reference Diode", "RF Diode", "Rectifier Diode"],
    correct: 3
  },
  {
    q: "In order to emit light, an L.E.D. (light emitting diode) must be __________",
    a: ["reverse biased", "forward biased", "unbiased", "none of the above"],
    correct: 1
  },
  {
    q: "What is an electromechanical device having one or more contacts opened and closed by a magnetic field generated by its own built-in electromagnet that can be activated by an external circuit?",
    a: ["Relay", "Switch", "Transformer", "Mouse"],
    correct: 0
  },
  {
    q: "An important figure of merit for power amplifiers is its gain. A transistor will have its Beta while a triode will have its __________.",
    a: ["Gamma", "Mu", "Omega", "Delta"],
    correct: 1
  },
  {
    q: "What capacitors are either electrolytic or tantalum type which are used like battery, i.e, with reference to polarity of terminals?",
    a: ["Trimpots", "Polarized", "Transducers", "Ultrasonics"],
    correct: 1
  },
  {
    q: "While the turns ratio of a transformer is the same as voltage ratio between a primary and secondary windings, the impedance ratio is __________.",
    a: [
      "the square of the turns ratio",
      "the square root of the voltage ratio",
      "same as the ratio of the current",
      "twice the turns ratio"
    ],
    correct: 0
  },
  {
    q: "Which of the following solid state devices is most like a vacuum tube in its general operating characteristics?",
    a: ["A bipolar transistor", "A tunnel diode", "A varistor", "A field Effect Transistor"],
    correct: 3
  },
  {
    q: "What type of capacitor may be connected either way in a circuit, i.e., without polarity consideration, usually applied in audio and RF circuits and as suppressors?",
    a: ["Polarized", "Fixed non-polarized", "Triac", "Quad Transistor"],
    correct: 2
  },
  {
    q: "The capacitors with the highest voltage ratings for use with high power tuned circuit of a legal limit tube RF amplifier will have a dielectric of __________.",
    a: ["silvered mica", "glass", "air", "vacuum"],
    correct: 0
  },
  {
    q: "What is a device used to convert electrical energy into sound?",
    a: ["LED", "Loudspeaker", "Microphone", "LCD"],
    correct: 1
  },
  {
    q: "A diode rectifier configuration which produces a full wave output and requires no center tap in the transformer secondary winding of a power transformer is __________.",
    a: [
      "single diode configuration",
      "full wave two diode configuration",
      "bridge configuration",
      "two parallel diode configuration"
    ],
    correct: 3
  },
  {
    q: "When the polarity of voltage is incorrect, the diode acts as a very high resistance that does not allow conduction and is said to be in what condition?",
    a: ["Off state", "Forward bias", "Idle", "Reverse bias"],
    correct: 3
  },
  {
    q: "Which statement is true?",
    a: [
      "An SCR (silicon controlled rectifier) will conduct when triggered at its gate regardless of the biasing of the anode and the cathode.",
      "When an SCR is triggered at its gate, the SCR keeps on conducting as long as the two other terminals are forward biased.",
      "The SCR will conduct only when triggered at the gate and if the two other terminals are reverse biased.",
      "The SCR will conduct only when the trigger voltage is present at its gate and the two other terminals are forward biased."
    ],
    correct: 1
  },
  {
    q: "What is a meter used to measure voltage and is connected in parallel to the circuit?",
    a: ["Moisture meter", "Voltmeter", "Galvanometer", "Ammeter"],
    correct: 1
  },
  {
    q: "When they were first developed, the chief advantage of CMOS digital circuits over the standard 7400 TTL series digital circuits is __________.",
    a: [
      "they are faster in operation",
      "both can operate at 5 volts power supply",
      "its lower power consumption",
      "was never found"
    ],
    correct: 2
  },
  {
    q: "Although phase locked loop (PLL) oscillator is very popular, for critical applications a simple crystal oscillator will outperform it because of __________.",
    a: ["lower cost", "lower phase noise", "frequency agility", "high harmonic content in its output"],
    correct: 2
  },
  {
    q: "What is another rectifier device used primarily for demodulation or separating the audio signal from a modulated carrier wave?",
    a: ["Light Emitting Diode", "Zener Diode", "Bridge Rectifier", "Signal Crystal Diode"],
    correct: 3
  },
  {
    q: "The Beta of a transistor is its __________.",
    a: [
      "plate resistance of the transistor",
      "current amplification factor",
      "transconductance",
      "mutual conductance"
    ],
    correct: 2
  },
  {
    q: "What is an electronic device intended to convert sound waves into electrical signals?",
    a: ["Microphone", "LCD", "LED", "Transistor"],
    correct: 0
  },
  {
    q: "A CMOS logic circuit will generally have a fan-out of __________.",
    a: [
      "1",
      "lower than a standard 7400 TTL (transistor-transistor logic)",
      "higher than a standard 7400 TTL",
      "less than 1"
    ],
    correct: 2
  },
  {
    q: "All quartz crystals used in communications, rely on utilizing the __________.",
    a: ["photoelectric effect", "hall effect", "piezoelectric effect", "Faraday effect"],
    correct: 2
  },
  {
    q: "The closest semiconductor “equivalent” to a vacuum tube triode is __________.",
    a: [
      "an NPN bipolar transistor",
      "a silicon controlled rectifier",
      "a field effect transistor",
      "a Schottky diode"
    ],
    correct: 2
  },
  {
    q: "What is a semiconductor device with both the active and passive elements contained in a single package to perform a complete electronic function?",
    a: ["Printed Circuit Board", "Integrated Circuit (IC)", "Microphone", "Transistor"],
    correct: 1
  },
  {
    q: "The very popular SANWA 360TR analog mulimeter and its various clones utilizes the D’Arsonval-Weston meter movement which is basically __________.",
    a: ["moving magnet system", "moving coil system", "tangent galvanometer", "Thomson galvanometer"],
    correct: 1
  },
  {
    q: "In electronics components, capacitors and inductors have reactance. Capacitors do not like a sudden change in __________.",
    a: ["applied voltage", "current flowing through it", "its resistance", "its capacitance value"],
    correct: 0
  },
  {
    q: "The TRIAC (Triode for Alternating Current) is virtually __________.",
    a: [
      "two NPN bipolar transistors back to back",
      "two N-channel Junction FETs back to back",
      "two CMOS FETs back to back",
      "two SCRs (silicon controlled rectifiers) back to back"
    ],
    correct: 3
  },
  {
    q: "What electronic device that is made up of two conductive surfaces that are separated from each other by a dielectric? This dielectric can be any insulating material such as paper, oil, plastic, mica, glass or even air.",
    a: ["Resistor", "Diode", "Capacitor", "Relay"],
    correct: 2
  },
  {
    q: "What is a resistor with a continuously adjustable resistance used for volume or brightness control?",
    a: ["Potentiometer", "Coil", "Transistor", "Capacitor"],
    correct: 0
  },
  {
    q: "The simple and lowly neon lamp technology has enjoyed a revival in recent years with the invention of __________.",
    a: ["cathode ray television", "LCD television", "LED television", "Plasma television"],
    correct: 2
  },
  {
    q: "In radio parlance, a “balun transformer” is __________.",
    a: [
      "balanced line to unbalanced line transformer",
      "balanced impedance to unbalanced impedance transformer",
      "balanced voltage to unbalanced voltage transformer",
      "balanced current to unbalanced current transformer"
    ],
    correct: 0
  },
  {
    q: "The important feature of an NPN common collector transistor is __________.",
    a: ["high voltage gain", "high input impedance", "low cost", "high output impedance"],
    correct: 1
  },
  {
    q: "Large capacitors are used in power supplies to smoothen the voltage output of the bridge diode rectifiers by being wired __________ an inductor at the output of the rectifier.",
    a: [
      "in series with",
      "parallel to",
      "in series and parallel combination with",
      "in series combination with"
    ],
    correct: 1
  },
  {
    q: "What is made of a wafer of natural quartz or any piezoelectric material having a definite thickness that makes it vibrate at a predetermined frequency when connected in a circuit and used in oscillator circuits and clocks?",
    a: ["Microphone", "Crystal", "Loudspeaker", "Capacitor"],
    correct: 1
  },
  {
    q: "Large electrolytic DC capacitors have to be wired in circuit observing the proper polarity because a wrong polarity wiring may result in __________.",
    a: [
      "inefficient performance",
      "decreased capacitance value",
      "decreased current capacity",
      "production of gases in the electrolyte which can cause an explosion"
    ],
    correct: 3
  },
  {
    q: "What is a p-n device which is like a rectifier diode except that it is usually intended to indicate flow of current, as a power ON indicator or condition of a circuit?",
    a: ["LED", "Loudspeaker", "Microphone", "LCD"],
    correct: 0
  },
  {
    q: "What is an electrical device consisting of two or more coils coupled together by magnetic induction usually converting 220V AC line to a lower secondary winding voltage for DC power supplies?",
    a: ["Transformer", "Tuning Coil", "Relay", "Electromagnet"],
    correct: 0
  },
  {
    q: "What is a protective device having a short length of wire that melts when the current that passes through it exceeds a predetermined (rated) value?",
    a: ["Terminal Post", "Soldering Lead", "Pilot Lamp", "Fuse"],
    correct: 3
  },
  {
    q: "The Zener diode serves as a good simple voltage reference because it maintains a relatively constant voltage across it when __________.",
    a: ["forward biased", "reversed biased", "unbiased", "biased by an alternating voltage"],
    correct: 1
  },
  {
    q: "What device is used in electronic circuits to introduce inductance, frequently found in tuning and filter circuits?",
    a: ["Transistor", "Coil", "Thermistor", "Potentiometer"],
    correct: 1
  },
  {
    q: "LCD (liquid crystal display) digital multi meters are fast replacing D’Arsonval Weston analog meter, LCDs feature a sealed glass panel containing a “liquid crystal”. The molecules of the liquid crystal are made to twist so that they can channel light between two polarizing plastic sheets by subjecting them to __________.",
    a: ["an electric field", "fluctuating magnetic field", "steady magnetic field", "plasma field"],
    correct: 0
  },
  {
    q: "Although made obsolete with the invention of the diac, what non-solid state device is a good component to use in triggering SCRs (silicon controlled rectifier) and TRIACs?",
    a: ["zener diode", "gas triode", "neon lamp", "tetrode"],
    correct: 2
  },
  {
    q: "Which of these works on the same principle as a CFL (compact fluorescent lamp)?",
    a: ["light emitting diode", "incandescent lamp", "neon lamp", "none of the above"],
    correct: 1
  },
  {
    q: "What is a two terminal device that conducts current easier in only one direction?",
    a: ["Fuse", "Diode", "Ammeter", "Multitester"],
    correct: 1
  }
];
